import { Component, OnInit } from '@angular/core';
import * as $ from 'jquery';
import * as moment from 'moment';
import { AuthService } from '../shared/services/auth.service';
import { takeWhile } from 'rxjs/operators';
import { Router } from '@angular/router';
import { of } from 'rxjs';

const serverResponse = {
  "metric": "footfall",
  "legend": {
      "Index": [
          6,
          1322,
          2638,
          3954,
          5270,
          6586,
          7902,
          9218,
          10534,
          11850,
          13166,
          14482,
          15798,
          17114,
          18430,
          19746,
          21062,
          22378,
          23694,
          25010,
          26326,
          27642,
          28958,
          30274,
          31590,
          32906,
          34222,
          35538,
          36854,
          38170,
          39486,
          40802,
          42118,
          43434,
          44750,
          46066,
          47381,
          48697,
          50013,
          51329,
          52645,
          53961,
          55277,
          56593,
          57909,
          59225,
          60541,
          61857,
          63173,
          64489,
          65805,
          67121,
          68437,
          69753,
          71069,
          72385,
          73701,
          75017,
          76333,
          77649,
          78965,
          80281,
          81597,
          82913,
          84229,
          85545,
          86861,
          88177,
          89493,
          90809,
          92125,
          93441,
          94757,
          96073,
          97389,
          98705,
          100021,
          101337,
          102653,
          103969,
          105285,
          106601,
          107917,
          109233,
          110549,
          111865,
          113181,
          114497,
          115813,
          117129,
          118445,
          119761,
          121077,
          122393,
          123709,
          125025,
          126341,
          127657,
          128973,
          130289,
          131605,
          132921,
          134237,
          135553,
          136869,
          138185,
          139501,
          140817,
          142132,
          143448,
          144764,
          146080,
          147396,
          148712,
          150028,
          151344,
          152660,
          153976,
          155292,
          156608,
          157924,
          159240,
          160556,
          161872,
          163188,
          164504,
          165820,
          167136,
          168452,
          169768,
          171084,
          172400,
          173716,
          175032,
          176348,
          177664,
          178980,
          180296,
          181612,
          182928,
          184244,
          185560,
          186876,
          188192
      ],
      "footfall_hex": [
          "#000080",
          "#000481",
          "#000782",
          "#000b83",
          "#000f84",
          "#001384",
          "#001685",
          "#001a86",
          "#001e87",
          "#028",
          "#002689",
          "#002a8a",
          "#002f8b",
          "#00338c",
          "#00378c",
          "#003b8d",
          "#00408e",
          "#00448f",
          "#004890",
          "#004d91",
          "#005292",
          "#005693",
          "#005b94",
          "#005f94",
          "#006495",
          "#006996",
          "#006e97",
          "#007398",
          "#007899",
          "#007d9a",
          "#00829b",
          "#00879c",
          "#008c9c",
          "#00919d",
          "#00969e",
          "#009c9f",
          "#00a09f",
          "#00a19b",
          "#00a298",
          "#00a394",
          "#00a490",
          "#00a48c",
          "#00a588",
          "#00a684",
          "#00a781",
          "#00a87d",
          "#00a978",
          "#00aa74",
          "#00ab70",
          "#00ac6c",
          "#00ac68",
          "#00ad63",
          "#00ae5f",
          "#00af5b",
          "#00b056",
          "#00b152",
          "#00b24d",
          "#00b348",
          "#00b444",
          "#00b43f",
          "#00b53a",
          "#00b636",
          "#00b731",
          "#00b82c",
          "#00b927",
          "#00ba22",
          "#00bb1d",
          "#00bc18",
          "#00bc12",
          "#00bd0d",
          "#00be08",
          "#00bf03",
          "#03c000",
          "#08c100",
          "#0ec200",
          "#13c300",
          "#19c300",
          "#1ec400",
          "#24c500",
          "#2ac600",
          "#2fc700",
          "#35c800",
          "#3bc900",
          "#41ca00",
          "#47cb00",
          "#4dcb00",
          "#53cc00",
          "#59cd00",
          "#5fce00",
          "#65cf00",
          "#6cd000",
          "#72d100",
          "#78d200",
          "#7fd300",
          "#85d300",
          "#8cd400",
          "#92d500",
          "#99d600",
          "#9fd700",
          "#a6d800",
          "#add900",
          "#b4da00",
          "#badb00",
          "#c1db00",
          "#c8dc00",
          "#cfdd00",
          "#d6de00",
          "#dddf00",
          "#e0db00",
          "#e1d600",
          "#e2d000",
          "#e3cb00",
          "#e3c500",
          "#e4c000",
          "#e5ba00",
          "#e6b400",
          "#e7ae00",
          "#e8a900",
          "#e9a300",
          "#ea9d00",
          "#eb9700",
          "#eb9100",
          "#ec8b00",
          "#ed8500",
          "#ee7f00",
          "#ef7800",
          "#f07200",
          "#f16c00",
          "#f26500",
          "#f35f00",
          "#f35900",
          "#f45200",
          "#f54b00",
          "#f64500",
          "#f73e00",
          "#f83700",
          "#f93100",
          "#fa2a00",
          "#fb2300",
          "#fb1c00",
          "#fc1500",
          "#fd0e00",
          "#fe0700",
          "#f00"
      ]
  },
  "data": {
      "lower_ground": {
          "concourse": {
              "brand_name_display": "Railway Concourse",
              "floor_display": "Lower Ground",
              "footfall": "14.65K",
              "repeat_footfall": "12.24K",
              "new_footfall": "2.4K",
              "footfall_hours": "1.72K",
              "avg_dwell_time": 7,
              "footfall_hex": "#002a8a",
              "d_footfall": 11,
              "d_repeat_footfall": 8,
              "d_new_footfall": 29,
              "d_footfall_hours": 7,
              "d_avg_dwell_time": 0,
              "color_index": 4
          },
          "homecenter": {
              "brand_name_display": "Home Center",
              "floor_display": "Lower Ground",
              "footfall": "33.22K",
              "repeat_footfall": "27.46K",
              "new_footfall": "5.76K",
              "footfall_hours": "28.63K",
              "avg_dwell_time": 52,
              "footfall_hex": "#006996",
              "d_footfall": -12,
              "d_repeat_footfall": -12,
              "d_new_footfall": -15,
              "d_footfall_hours": -22,
              "d_avg_dwell_time": -12,
              "color_index": 10
          },
          "bigbazar": {
              "brand_name_display": "Big Bazaar",
              "floor_display": "Lower Ground",
              "footfall": "83.76K",
              "repeat_footfall": "66.38K",
              "new_footfall": "17.38K",
              "footfall_hours": "14.2K",
              "avg_dwell_time": 10,
              "footfall_hex": "#00b927",
              "d_footfall": -12,
              "d_repeat_footfall": -12,
              "d_new_footfall": -14,
              "d_footfall_hours": 10,
              "d_avg_dwell_time": 30,
              "color_index": 80
          }
      },
      "upper_ground": {
          "gas": {
              "brand_name_display": "GAS",
              "floor_display": "Upper Ground",
              "footfall": "1.24K",
              "repeat_footfall": "1.09K",
              "new_footfall": 144,
              "footfall_hours": 142,
              "avg_dwell_time": 7,
              "footfall_hex": "#000481",
              "d_footfall": -73,
              "d_repeat_footfall": -71,
              "d_new_footfall": -84,
              "d_footfall_hours": -58,
              "d_avg_dwell_time": 57
          },
          "innisfree": {
              "brand_name_display": "Innisfree",
              "floor_display": "Upper Ground",
              "footfall": "1.59K",
              "repeat_footfall": "1.37K",
              "new_footfall": 222,
              "footfall_hours": 90,
              "avg_dwell_time": 3,
              "footfall_hex": "#000481",
              "d_footfall": 10,
              "d_repeat_footfall": 12,
              "d_new_footfall": -3,
              "d_footfall_hours": 7,
              "d_avg_dwell_time": 0
          },
          "sephora": {
              "brand_name_display": "Sephora",
              "floor_display": "Upper Ground",
              "footfall": "2.28K",
              "repeat_footfall": "1.93K",
              "new_footfall": 342,
              "footfall_hours": 188,
              "avg_dwell_time": 5,
              "footfall_hex": "#000481",
              "d_footfall": -70,
              "d_repeat_footfall": -68,
              "d_new_footfall": -81,
              "d_footfall_hours": -81,
              "d_avg_dwell_time": -40
          },
          "helvetica": {
              "brand_name_display": "Helvetica",
              "floor_display": "Upper Ground",
              "footfall": "1.84K",
              "repeat_footfall": "1.57K",
              "new_footfall": 262,
              "footfall_hours": 121,
              "avg_dwell_time": 4,
              "footfall_hex": "#000481",
              "d_footfall": 80,
              "d_repeat_footfall": 81,
              "d_new_footfall": 74,
              "d_footfall_hours": 90,
              "d_avg_dwell_time": 0
          },
          "amante": {
              "brand_name_display": "Amante",
              "floor_display": "Upper Ground",
              "footfall": "3.35K",
              "repeat_footfall": "2.59K",
              "new_footfall": 761,
              "footfall_hours": 500,
              "avg_dwell_time": 9,
              "footfall_hex": "#000782",
              "d_footfall": 9,
              "d_repeat_footfall": 10,
              "d_new_footfall": 6,
              "d_footfall_hours": 12,
              "d_avg_dwell_time": 0
          },
          "organic_harvest": {
              "brand_name_display": "Organic Harvest",
              "floor_display": "Upper Ground",
              "footfall": "4.49K",
              "repeat_footfall": "3.74K",
              "new_footfall": 748,
              "footfall_hours": 206,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -31,
              "d_repeat_footfall": -31,
              "d_new_footfall": -30,
              "d_footfall_hours": -38,
              "d_avg_dwell_time": -33
          },
          "ethos": {
              "brand_name_display": "Ethos",
              "floor_display": "Upper Ground",
              "footfall": "2.95K",
              "repeat_footfall": "2.44K",
              "new_footfall": 507,
              "footfall_hours": 257,
              "avg_dwell_time": 5,
              "footfall_hex": "#000782",
              "d_footfall": -5,
              "d_repeat_footfall": -1,
              "d_new_footfall": -22,
              "d_footfall_hours": 49,
              "d_avg_dwell_time": 60
          },
          "adamis": {
              "brand_name_display": "Adamis",
              "floor_display": "Upper Ground",
              "footfall": "4.19K",
              "repeat_footfall": "3.45K",
              "new_footfall": 744,
              "footfall_hours": 194,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -17,
              "d_repeat_footfall": -15,
              "d_new_footfall": -23,
              "d_footfall_hours": -15,
              "d_avg_dwell_time": 0
          },
          "sunglass_hut": {
              "brand_name_display": "Sunglass Hut",
              "floor_display": "Upper Ground",
              "footfall": "4.5K",
              "repeat_footfall": "3.77K",
              "new_footfall": 728,
              "footfall_hours": 204,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -29,
              "d_repeat_footfall": -27,
              "d_new_footfall": -36,
              "d_footfall_hours": -23,
              "d_avg_dwell_time": 0
          },
          "promod": {
              "brand_name_display": "Promod",
              "floor_display": "Upper Ground",
              "footfall": "4.69K",
              "repeat_footfall": "3.83K",
              "new_footfall": 859,
              "footfall_hours": 333,
              "avg_dwell_time": 4,
              "footfall_hex": "#000782",
              "d_footfall": -24,
              "d_repeat_footfall": -21,
              "d_new_footfall": -33,
              "d_footfall_hours": -8,
              "d_avg_dwell_time": 25
          },
          "hush_puppies": {
              "brand_name_display": "Hush Puppies",
              "floor_display": "Upper Ground",
              "footfall": "3.21K",
              "repeat_footfall": "2.7K",
              "new_footfall": 508,
              "footfall_hours": 150,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -17,
              "d_repeat_footfall": -15,
              "d_new_footfall": -26,
              "d_footfall_hours": -17,
              "d_avg_dwell_time": 0
          },
          "brooks": {
              "brand_name_display": "Brooks",
              "floor_display": "Upper Ground",
              "footfall": "3.33K",
              "repeat_footfall": "2.8K",
              "new_footfall": 530,
              "footfall_hours": 494,
              "avg_dwell_time": 9,
              "footfall_hex": "#000782",
              "d_footfall": -33,
              "d_repeat_footfall": -33,
              "d_new_footfall": -33,
              "d_footfall_hours": -53,
              "d_avg_dwell_time": -33
          },
          "looks_salon": {
              "brand_name_display": " LOOKS Salon ",
              "floor_display": "Upper Ground",
              "footfall": "3.73K",
              "repeat_footfall": "3.13K",
              "new_footfall": 595,
              "footfall_hours": 258,
              "avg_dwell_time": 4,
              "footfall_hex": "#000782",
              "d_footfall": -14,
              "d_repeat_footfall": -12,
              "d_new_footfall": -23,
              "d_footfall_hours": -4,
              "d_avg_dwell_time": 25
          },
          "swatch": {
              "brand_name_display": "Swatch",
              "floor_display": "Upper Ground",
              "footfall": "3.52K",
              "repeat_footfall": "2.87K",
              "new_footfall": 644,
              "footfall_hours": 233,
              "avg_dwell_time": 4,
              "footfall_hex": "#000782",
              "d_footfall": -35,
              "d_repeat_footfall": -33,
              "d_new_footfall": -44,
              "d_footfall_hours": -23,
              "d_avg_dwell_time": 25
          },
          "nyassa": {
              "brand_name_display": "Nyassa",
              "floor_display": "Upper Ground",
              "footfall": "5.15K",
              "repeat_footfall": "4.14K",
              "new_footfall": "1.01K",
              "footfall_hours": 252,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": -3,
              "d_repeat_footfall": -3,
              "d_new_footfall": -3,
              "d_footfall_hours": -3,
              "d_avg_dwell_time": 0
          },
          "coverstory": {
              "brand_name_display": "Cover Story",
              "floor_display": "Upper Ground",
              "footfall": "6.03K",
              "repeat_footfall": "4.92K",
              "new_footfall": "1.11K",
              "footfall_hours": 349,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": -5,
              "d_repeat_footfall": -3,
              "d_new_footfall": -14,
              "d_footfall_hours": 1,
              "d_avg_dwell_time": 33
          },
          "superdry": {
              "brand_name_display": "Super Dry",
              "floor_display": "Upper Ground",
              "footfall": "5.04K",
              "repeat_footfall": "4.18K",
              "new_footfall": 859,
              "footfall_hours": 294,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": -26,
              "d_repeat_footfall": -26,
              "d_new_footfall": -25,
              "d_footfall_hours": -25,
              "d_avg_dwell_time": 33
          },
          "adidas_originals": {
              "brand_name_display": "Adidas Originals",
              "floor_display": "Upper Ground",
              "footfall": "5.86K",
              "repeat_footfall": "4.94K",
              "new_footfall": 921,
              "footfall_hours": 294,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": -24,
              "d_repeat_footfall": -21,
              "d_new_footfall": -35,
              "d_footfall_hours": -17,
              "d_avg_dwell_time": 0
          },
          "raymond": {
              "brand_name_display": "Raymond",
              "floor_display": "Upper Ground",
              "footfall": "6.4K",
              "repeat_footfall": "5.19K",
              "new_footfall": "1.21K",
              "footfall_hours": 691,
              "avg_dwell_time": 6,
              "footfall_hex": "#000f84",
              "d_footfall": 20,
              "d_repeat_footfall": 20,
              "d_new_footfall": 18,
              "d_footfall_hours": 2,
              "d_avg_dwell_time": 0
          },
          "steve_madden": {
              "brand_name_display": "Steve madden",
              "floor_display": "Upper Ground",
              "footfall": "5.92K",
              "repeat_footfall": "4.98K",
              "new_footfall": 939,
              "footfall_hours": 478,
              "avg_dwell_time": 5,
              "footfall_hex": "#000f84",
              "d_footfall": 35,
              "d_repeat_footfall": 35,
              "d_new_footfall": 31,
              "d_footfall_hours": 47,
              "d_avg_dwell_time": 0
          },
          "gutereise": {
              "brand_name_display": "Gutereise",
              "floor_display": "Upper Ground",
              "footfall": "4.79K",
              "repeat_footfall": "3.92K",
              "new_footfall": 866,
              "footfall_hours": 250,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": -32,
              "d_repeat_footfall": -33,
              "d_new_footfall": -30,
              "d_footfall_hours": -23,
              "d_avg_dwell_time": 33
          },
          "Sephora": {
              "brand_name_display": "Sephora",
              "floor_display": "Upper Ground",
              "footfall": "7.94K",
              "repeat_footfall": "6.4K",
              "new_footfall": "1.54K",
              "footfall_hours": 435,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -33,
              "d_repeat_footfall": -32,
              "d_new_footfall": -38,
              "d_footfall_hours": -29,
              "d_avg_dwell_time": 0
          },
          "charles_keith": {
              "brand_name_display": "Charles & Keith",
              "floor_display": "Upper Ground",
              "footfall": "8.19K",
              "repeat_footfall": "6.69K",
              "new_footfall": "1.49K",
              "footfall_hours": 454,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -34,
              "d_repeat_footfall": -34,
              "d_new_footfall": -35,
              "d_footfall_hours": -39,
              "d_avg_dwell_time": 0
          },
          "selected": {
              "brand_name_display": "Selected",
              "floor_display": "Upper Ground",
              "footfall": "6.81K",
              "repeat_footfall": "5.69K",
              "new_footfall": "1.12K",
              "footfall_hours": 374,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -15,
              "d_repeat_footfall": -13,
              "d_new_footfall": -26,
              "d_footfall_hours": -15,
              "d_avg_dwell_time": 0
          },
          "trueblue": {
              "brand_name_display": "True Blue",
              "floor_display": "Upper Ground",
              "footfall": "7.1K",
              "repeat_footfall": "5.69K",
              "new_footfall": "1.41K",
              "footfall_hours": 334,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -22,
              "d_repeat_footfall": -22,
              "d_new_footfall": -22,
              "d_footfall_hours": -23,
              "d_avg_dwell_time": 0
          },
          "zodiac": {
              "brand_name_display": "Zodiac",
              "floor_display": "Upper Ground",
              "footfall": "6.72K",
              "repeat_footfall": "5.38K",
              "new_footfall": "1.34K",
              "footfall_hours": 454,
              "avg_dwell_time": 4,
              "footfall_hex": "#001384",
              "d_footfall": 11,
              "d_repeat_footfall": 13,
              "d_new_footfall": 3,
              "d_footfall_hours": 30,
              "d_avg_dwell_time": 25
          },
          "parcos": {
              "brand_name_display": "Parcos",
              "floor_display": "Upper Ground",
              "footfall": "7.56K",
              "repeat_footfall": "6.11K",
              "new_footfall": "1.45K",
              "footfall_hours": 439,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -32,
              "d_repeat_footfall": -31,
              "d_new_footfall": -35,
              "d_footfall_hours": -32,
              "d_avg_dwell_time": 0
          },
          "gant": {
              "brand_name_display": "Gant",
              "floor_display": "Upper Ground",
              "footfall": "6.8K",
              "repeat_footfall": "5.55K",
              "new_footfall": "1.25K",
              "footfall_hours": 400,
              "avg_dwell_time": 4,
              "footfall_hex": "#001384",
              "d_footfall": 18,
              "d_repeat_footfall": 19,
              "d_new_footfall": 14,
              "d_footfall_hours": 30,
              "d_avg_dwell_time": 0
          },
          "rare_rabbit": {
              "brand_name_display": "Rare Rabbit",
              "floor_display": "Upper Ground",
              "footfall": "7.63K",
              "repeat_footfall": "6.22K",
              "new_footfall": "1.41K",
              "footfall_hours": 417,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -11,
              "d_repeat_footfall": -10,
              "d_new_footfall": -17,
              "d_footfall_hours": 6,
              "d_avg_dwell_time": 33
          },
          "chaayos": {
              "brand_name_display": "Chaayos",
              "floor_display": "Upper Ground",
              "footfall": "10.31K",
              "repeat_footfall": "8.42K",
              "new_footfall": "1.88K",
              "footfall_hours": 707,
              "avg_dwell_time": 4,
              "footfall_hex": "#001a86",
              "d_footfall": 1,
              "d_repeat_footfall": 3,
              "d_new_footfall": -5,
              "d_footfall_hours": 7,
              "d_avg_dwell_time": 0
          },
          "rosso_brunello": {
              "brand_name_display": "Rosso Brunello",
              "floor_display": "Upper Ground",
              "footfall": "10.01K",
              "repeat_footfall": "8.12K",
              "new_footfall": "1.89K",
              "footfall_hours": 806,
              "avg_dwell_time": 5,
              "footfall_hex": "#001a86",
              "d_footfall": -19,
              "d_repeat_footfall": -18,
              "d_new_footfall": -25,
              "d_footfall_hours": -19,
              "d_avg_dwell_time": 0
          },
          "aeropostale": {
              "brand_name_display": "Aeropostale",
              "floor_display": "Upper Ground",
              "footfall": "9.21K",
              "repeat_footfall": "7.02K",
              "new_footfall": "2.19K",
              "footfall_hours": "1.1K",
              "avg_dwell_time": 7,
              "footfall_hex": "#001a86",
              "d_footfall": 15,
              "d_repeat_footfall": 17,
              "d_new_footfall": 8,
              "d_footfall_hours": 26,
              "d_avg_dwell_time": 14
          },
          "ugf_promoarea_1": {
              "brand_name_display": "",
              "floor_display": "Upper Ground",
              "footfall": "9.96K",
              "repeat_footfall": "8.03K",
              "new_footfall": "1.93K",
              "footfall_hours": 670,
              "avg_dwell_time": 4,
              "footfall_hex": "#001a86",
              "d_footfall": -31,
              "d_repeat_footfall": -30,
              "d_new_footfall": -35,
              "d_footfall_hours": -23,
              "d_avg_dwell_time": 0
          },
          "swarovski": {
              "brand_name_display": "Swarovski",
              "floor_display": "Upper Ground",
              "footfall": "9.16K",
              "repeat_footfall": "7.33K",
              "new_footfall": "1.83K",
              "footfall_hours": 521,
              "avg_dwell_time": 3,
              "footfall_hex": "#001a86",
              "d_footfall": -5,
              "d_repeat_footfall": -4,
              "d_new_footfall": -12,
              "d_footfall_hours": 1,
              "d_avg_dwell_time": 33
          },
          "ugf_promoarea_2": {
              "brand_name_display": "",
              "floor_display": "Upper Ground",
              "footfall": "9.86K",
              "repeat_footfall": "7.95K",
              "new_footfall": "1.91K",
              "footfall_hours": 594,
              "avg_dwell_time": 4,
              "footfall_hex": "#001a86",
              "d_footfall": -16,
              "d_repeat_footfall": -15,
              "d_new_footfall": -21,
              "d_footfall_hours": -26,
              "d_avg_dwell_time": -25
          },
          "damilano": {
              "brand_name_display": "Da Milano",
              "floor_display": "Upper Ground",
              "footfall": "9.31K",
              "repeat_footfall": "7.51K",
              "new_footfall": "1.8K",
              "footfall_hours": 511,
              "avg_dwell_time": 3,
              "footfall_hex": "#001a86",
              "d_footfall": 2,
              "d_repeat_footfall": 5,
              "d_new_footfall": -7,
              "d_footfall_hours": 5,
              "d_avg_dwell_time": 0
          },
          "only": {
              "brand_name_display": "Only",
              "floor_display": "Upper Ground",
              "footfall": "11.63K",
              "repeat_footfall": "9.59K",
              "new_footfall": "2.04K",
              "footfall_hours": 829,
              "avg_dwell_time": 4,
              "footfall_hex": "#001e87",
              "d_footfall": -15,
              "d_repeat_footfall": -14,
              "d_new_footfall": -23,
              "d_footfall_hours": -11,
              "d_avg_dwell_time": 25
          },
          "accesorize": {
              "brand_name_display": "Accessorize",
              "floor_display": "Upper Ground",
              "footfall": "11.46K",
              "repeat_footfall": "9.25K",
              "new_footfall": "2.21K",
              "footfall_hours": 855,
              "avg_dwell_time": 4,
              "footfall_hex": "#001e87",
              "d_footfall": -1,
              "d_repeat_footfall": 1,
              "d_new_footfall": -8,
              "d_footfall_hours": 15,
              "d_avg_dwell_time": 25
          },
          "mac": {
              "brand_name_display": "MAC",
              "floor_display": "Upper Ground",
              "footfall": "11.26K",
              "repeat_footfall": "8.97K",
              "new_footfall": "2.29K",
              "footfall_hours": 581,
              "avg_dwell_time": 3,
              "footfall_hex": "#001e87",
              "d_footfall": -17,
              "d_repeat_footfall": -15,
              "d_new_footfall": -25,
              "d_footfall_hours": -19,
              "d_avg_dwell_time": 0
          },
          "chambor": {
              "brand_name_display": "Chambor",
              "floor_display": "Upper Ground",
              "footfall": "11.33K",
              "repeat_footfall": "8.85K",
              "new_footfall": "2.48K",
              "footfall_hours": 736,
              "avg_dwell_time": 4,
              "footfall_hex": "#001e87",
              "d_footfall": -1,
              "d_repeat_footfall": 0,
              "d_new_footfall": -5,
              "d_footfall_hours": 5,
              "d_avg_dwell_time": 0
          },
          "tissot": {
              "brand_name_display": "Tissot",
              "floor_display": "Upper Ground",
              "footfall": "10.62K",
              "repeat_footfall": "8.38K",
              "new_footfall": "2.24K",
              "footfall_hours": 588,
              "avg_dwell_time": 3,
              "footfall_hex": "#001e87",
              "d_footfall": -28,
              "d_repeat_footfall": -27,
              "d_new_footfall": -31,
              "d_footfall_hours": -33,
              "d_avg_dwell_time": 0
          },
          "nautica": {
              "brand_name_display": "Nautica",
              "floor_display": "Upper Ground",
              "footfall": "15.36K",
              "repeat_footfall": "11.69K",
              "new_footfall": "3.67K",
              "footfall_hours": "1.1K",
              "avg_dwell_time": 4,
              "footfall_hex": "#002a8a",
              "d_footfall": -44,
              "d_repeat_footfall": -45,
              "d_new_footfall": -39,
              "d_footfall_hours": -54,
              "d_avg_dwell_time": 0
          },
          "kama": {
              "brand_name_display": "Kama Ayurveda",
              "floor_display": "Upper Ground",
              "footfall": "14.34K",
              "repeat_footfall": "11.11K",
              "new_footfall": "3.23K",
              "footfall_hours": "1.17K",
              "avg_dwell_time": 5,
              "footfall_hex": "#002a8a",
              "d_footfall": -31,
              "d_repeat_footfall": -31,
              "d_new_footfall": -31,
              "d_footfall_hours": -54,
              "d_avg_dwell_time": -40
          },
          "tommyhilfigher": {
              "brand_name_display": "Tommy Hilfiger",
              "floor_display": "Upper Ground",
              "footfall": "15.7K",
              "repeat_footfall": "12.28K",
              "new_footfall": "3.42K",
              "footfall_hours": "1.45K",
              "avg_dwell_time": 6,
              "footfall_hex": "#002a8a",
              "d_footfall": -4,
              "d_repeat_footfall": -5,
              "d_new_footfall": -1,
              "d_footfall_hours": -13,
              "d_avg_dwell_time": -17
          },
          "hidesign": {
              "brand_name_display": "Hidesign",
              "floor_display": "Upper Ground",
              "footfall": "15.56K",
              "repeat_footfall": "12.27K",
              "new_footfall": "3.28K",
              "footfall_hours": "1.41K",
              "avg_dwell_time": 5,
              "footfall_hex": "#002a8a",
              "d_footfall": -11,
              "d_repeat_footfall": -10,
              "d_new_footfall": -15,
              "d_footfall_hours": -10,
              "d_avg_dwell_time": 20
          },
          "edhardy": {
              "brand_name_display": "Ed Hardy",
              "floor_display": "Upper Ground",
              "footfall": "14.37K",
              "repeat_footfall": "11.31K",
              "new_footfall": "3.06K",
              "footfall_hours": "1.33K",
              "avg_dwell_time": 6,
              "footfall_hex": "#002a8a",
              "d_footfall": -35,
              "d_repeat_footfall": -34,
              "d_new_footfall": -36,
              "d_footfall_hours": -57,
              "d_avg_dwell_time": -33
          },
          "maple": {
              "brand_name_display": "Maple",
              "floor_display": "Upper Ground",
              "footfall": "14.74K",
              "repeat_footfall": "11.6K",
              "new_footfall": "3.14K",
              "footfall_hours": "5.83K",
              "avg_dwell_time": 24,
              "footfall_hex": "#002a8a",
              "d_footfall": -6,
              "d_repeat_footfall": -7,
              "d_new_footfall": -6,
              "d_footfall_hours": 22,
              "d_avg_dwell_time": 29
          },
          "lacoste": {
              "brand_name_display": "Lacoste",
              "floor_display": "Upper Ground",
              "footfall": "16.11K",
              "repeat_footfall": "12.28K",
              "new_footfall": "3.83K",
              "footfall_hours": "1.6K",
              "avg_dwell_time": 6,
              "footfall_hex": "#002f8b",
              "d_footfall": 7,
              "d_repeat_footfall": 7,
              "d_new_footfall": 6,
              "d_footfall_hours": -5,
              "d_avg_dwell_time": -17
          },
          "lifestyle_sf": {
              "brand_name_display": "Lifestyle",
              "floor_display": "Upper Ground",
              "footfall": "16.89K",
              "repeat_footfall": "13.23K",
              "new_footfall": "3.66K",
              "footfall_hours": "2.6K",
              "avg_dwell_time": 9,
              "footfall_hex": "#002f8b",
              "d_footfall": -15,
              "d_repeat_footfall": -15,
              "d_new_footfall": -13,
              "d_footfall_hours": -11,
              "d_avg_dwell_time": 11
          },
          "forest_essential": {
              "brand_name_display": "Forest Essentials",
              "floor_display": "Upper Ground",
              "footfall": "17.58K",
              "repeat_footfall": "13.71K",
              "new_footfall": "3.87K",
              "footfall_hours": "1.4K",
              "avg_dwell_time": 5,
              "footfall_hex": "#002f8b",
              "d_footfall": -33,
              "d_repeat_footfall": -31,
              "d_new_footfall": -39,
              "d_footfall_hours": -29,
              "d_avg_dwell_time": 0
          },
          "colorbar": {
              "brand_name_display": "Colorbar",
              "floor_display": "Upper Ground",
              "footfall": "17.51K",
              "repeat_footfall": "13.7K",
              "new_footfall": "3.81K",
              "footfall_hours": "1.26K",
              "avg_dwell_time": 4,
              "footfall_hex": "#002f8b",
              "d_footfall": 1,
              "d_repeat_footfall": 2,
              "d_new_footfall": 0,
              "d_footfall_hours": 2,
              "d_avg_dwell_time": 0
          },
          "beinghuman": {
              "brand_name_display": "Being Human",
              "floor_display": "Upper Ground",
              "footfall": "16.63K",
              "repeat_footfall": "13.54K",
              "new_footfall": "3.09K",
              "footfall_hours": "1.16K",
              "avg_dwell_time": 4,
              "footfall_hex": "#002f8b",
              "d_footfall": -3,
              "d_repeat_footfall": 0,
              "d_new_footfall": -14,
              "d_footfall_hours": 6,
              "d_avg_dwell_time": 25
          },
          "tanishq": {
              "brand_name_display": "Tanishq",
              "floor_display": "Upper Ground",
              "footfall": "21.53K",
              "repeat_footfall": "17.29K",
              "new_footfall": "4.24K",
              "footfall_hours": "1.37K",
              "avg_dwell_time": 4,
              "footfall_hex": "#003b8d",
              "d_footfall": -3,
              "d_repeat_footfall": -2,
              "d_new_footfall": -7,
              "d_footfall_hours": 4,
              "d_avg_dwell_time": 0
          },
          "hunkemoller": {
              "brand_name_display": "Hunkemoller",
              "floor_display": "Upper Ground",
              "footfall": "23.36K",
              "repeat_footfall": "18.19K",
              "new_footfall": "5.17K",
              "footfall_hours": "2.09K",
              "avg_dwell_time": 5,
              "footfall_hex": "#00448f",
              "d_footfall": 4,
              "d_repeat_footfall": 6,
              "d_new_footfall": -2,
              "d_footfall_hours": 22,
              "d_avg_dwell_time": 20
          },
          "nykaa": {
              "brand_name_display": "Nykaa",
              "floor_display": "Upper Ground",
              "footfall": "22.51K",
              "repeat_footfall": "18.31K",
              "new_footfall": "4.2K",
              "footfall_hours": "1.56K",
              "avg_dwell_time": 4,
              "footfall_hex": "#00448f",
              "d_footfall": -13,
              "d_repeat_footfall": -13,
              "d_new_footfall": -14,
              "d_footfall_hours": -14,
              "d_avg_dwell_time": 0
          },
          "forever21": {
              "brand_name_display": "Forever 21",
              "floor_display": "Upper Ground",
              "footfall": "30.58K",
              "repeat_footfall": "24.29K",
              "new_footfall": "6.29K",
              "footfall_hours": "4.06K",
              "avg_dwell_time": 8,
              "footfall_hex": "#005b94",
              "d_footfall": -5,
              "d_repeat_footfall": -5,
              "d_new_footfall": -3,
              "d_footfall_hours": 22,
              "d_avg_dwell_time": 25
          },
          "camla": {
              "brand_name_display": "",
              "floor_display": "Upper Ground",
              "footfall": "29.35K",
              "repeat_footfall": "22.39K",
              "new_footfall": "6.96K",
              "footfall_hours": "3.67K",
              "avg_dwell_time": 8,
              "footfall_hex": "#005b94",
              "d_footfall": -4,
              "d_repeat_footfall": -2,
              "d_new_footfall": -8,
              "d_footfall_hours": 10,
              "d_avg_dwell_time": 12
          },
          "veromoda": {
              "brand_name_display": "Vero Moda",
              "floor_display": "Upper Ground",
              "footfall": "31.16K",
              "repeat_footfall": "24.16K",
              "new_footfall": "7.0K",
              "footfall_hours": "3.33K",
              "avg_dwell_time": 6,
              "footfall_hex": "#006495",
              "d_footfall": 8,
              "d_repeat_footfall": 9,
              "d_new_footfall": 6,
              "d_footfall_hours": 26,
              "d_avg_dwell_time": 17
          },
          "lifestyle_ff": {
              "brand_name_display": "Lifestyle",
              "floor_display": "Upper Ground",
              "footfall": "39.88K",
              "repeat_footfall": "31.14K",
              "new_footfall": "8.75K",
              "footfall_hours": "5.64K",
              "avg_dwell_time": 8,
              "footfall_hex": "#00829b",
              "d_footfall": -13,
              "d_repeat_footfall": -14,
              "d_new_footfall": -11,
              "d_footfall_hours": -33,
              "d_avg_dwell_time": -12
          },
          "starbucks": {
              "brand_name_display": "Starbucks",
              "floor_display": "Upper Ground",
              "footfall": "51.79K",
              "repeat_footfall": "38.64K",
              "new_footfall": "13.15K",
              "footfall_hours": "5.47K",
              "avg_dwell_time": 6,
              "footfall_hex": "#00a490",
              "d_footfall": -2,
              "d_repeat_footfall": -1,
              "d_new_footfall": -6,
              "d_footfall_hours": 6,
              "d_avg_dwell_time": 17
          },
          "hnm": {
              "brand_name_display": "H&M",
              "floor_display": "Upper Ground",
              "footfall": "68.77K",
              "repeat_footfall": "52.01K",
              "new_footfall": "16.76K",
              "footfall_hours": "12.3K",
              "avg_dwell_time": 11,
              "footfall_hex": "#00ae5f",
              "d_footfall": 1,
              "d_repeat_footfall": 1,
              "d_new_footfall": 0,
              "d_footfall_hours": 1,
              "d_avg_dwell_time": 0
          },
          "m_s": {
              "brand_name_display": "Marks & Spencer",
              "floor_display": "Upper Ground",
              "footfall": "72.91K",
              "repeat_footfall": "56.04K",
              "new_footfall": "16.86K",
              "footfall_hours": "10.2K",
              "avg_dwell_time": 8,
              "footfall_hex": "#00b152",
              "d_footfall": -29,
              "d_repeat_footfall": -29,
              "d_new_footfall": -27,
              "d_footfall_hours": -37,
              "d_avg_dwell_time": -12
          },
          "lifestyle_ugf": {
              "brand_name_display": "Lifestyle",
              "floor_display": "Upper Ground",
              "footfall": "73.53K",
              "repeat_footfall": "56.43K",
              "new_footfall": "17.1K",
              "footfall_hours": "16.37K",
              "avg_dwell_time": 13,
              "footfall_hex": "#00b152",
              "d_footfall": -24,
              "d_repeat_footfall": -25,
              "d_new_footfall": -23,
              "d_footfall_hours": -32,
              "d_avg_dwell_time": -8
          }
      },
      "first_floor": {
          "reebok": {
              "brand_name_display": "Reebok",
              "floor_display": "First Floor",
              "footfall": 285,
              "repeat_footfall": 230,
              "new_footfall": 55,
              "footfall_hours": 13,
              "avg_dwell_time": 3,
              "footfall_hex": "#000080",
              "d_footfall": -26,
              "d_repeat_footfall": -20,
              "d_new_footfall": -51,
              "d_footfall_hours": 31,
              "d_avg_dwell_time": 67
          },
          "zivame": {
              "brand_name_display": "Zivame",
              "floor_display": "First Floor",
              "footfall": 114,
              "repeat_footfall": 82,
              "new_footfall": 32,
              "footfall_hours": 0,
              "avg_dwell_time": 0,
              "footfall_hex": "#000080",
              "d_footfall": 44,
              "d_repeat_footfall": 51,
              "d_new_footfall": 25,
              "d_footfall_hours": "",
              "d_avg_dwell_time": ""
          },
          "uspa": {
              "brand_name_display": "USPA",
              "floor_display": "First Floor",
              "footfall": 254,
              "repeat_footfall": 221,
              "new_footfall": 33,
              "footfall_hours": 19,
              "avg_dwell_time": 4,
              "footfall_hex": "#000080",
              "d_footfall": 52,
              "d_repeat_footfall": 47,
              "d_new_footfall": 85,
              "d_footfall_hours": 26,
              "d_avg_dwell_time": 0
          },
          "color_plus": {
              "brand_name_display": "ColorPlus",
              "floor_display": "First Floor",
              "footfall": "2.14K",
              "repeat_footfall": "1.79K",
              "new_footfall": 347,
              "footfall_hours": 101,
              "avg_dwell_time": 3,
              "footfall_hex": "#000481",
              "d_footfall": 13,
              "d_repeat_footfall": 12,
              "d_new_footfall": 18,
              "d_footfall_hours": 28,
              "d_avg_dwell_time": 0
          },
          "us_polo": {
              "brand_name_display": "US POLO Denim",
              "floor_display": "First Floor",
              "footfall": "1.21K",
              "repeat_footfall": "1.0K",
              "new_footfall": 209,
              "footfall_hours": 54,
              "avg_dwell_time": 3,
              "footfall_hex": "#000481",
              "d_footfall": 10,
              "d_repeat_footfall": 12,
              "d_new_footfall": 2,
              "d_footfall_hours": 20,
              "d_avg_dwell_time": 0
          },
          "van_heusen": {
              "brand_name_display": "Van Heusen",
              "floor_display": "First Floor",
              "footfall": "2.31K",
              "repeat_footfall": "1.97K",
              "new_footfall": 344,
              "footfall_hours": 135,
              "avg_dwell_time": 4,
              "footfall_hex": "#000481",
              "d_footfall": 97,
              "d_repeat_footfall": 100,
              "d_new_footfall": 77,
              "d_footfall_hours": 121,
              "d_avg_dwell_time": 0
          },
          "trends": {
              "brand_name_display": "Reliance Trends",
              "floor_display": "First Floor",
              "footfall": "1.67K",
              "repeat_footfall": "1.36K",
              "new_footfall": 304,
              "footfall_hours": 82,
              "avg_dwell_time": 3,
              "footfall_hex": "#000481",
              "d_footfall": -15,
              "d_repeat_footfall": -16,
              "d_new_footfall": -8,
              "d_footfall_hours": -16,
              "d_avg_dwell_time": 0
          },
          "lenskart": {
              "brand_name_display": "Lenskart",
              "floor_display": "First Floor",
              "footfall": "2.33K",
              "repeat_footfall": "1.92K",
              "new_footfall": 409,
              "footfall_hours": 116,
              "avg_dwell_time": 3,
              "footfall_hex": "#000481",
              "d_footfall": -16,
              "d_repeat_footfall": -16,
              "d_new_footfall": -14,
              "d_footfall_hours": -14,
              "d_avg_dwell_time": 0
          },
          "and": {
              "brand_name_display": "AND",
              "floor_display": "First Floor",
              "footfall": "3.94K",
              "repeat_footfall": "3.16K",
              "new_footfall": 776,
              "footfall_hours": 197,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -3,
              "d_repeat_footfall": -2,
              "d_new_footfall": -9,
              "d_footfall_hours": 4,
              "d_avg_dwell_time": 0
          },
          "allen_solly": {
              "brand_name_display": "Allensolly",
              "floor_display": "First Floor",
              "footfall": "4.17K",
              "repeat_footfall": "3.4K",
              "new_footfall": 768,
              "footfall_hours": 254,
              "avg_dwell_time": 4,
              "footfall_hex": "#000782",
              "d_footfall": -1,
              "d_repeat_footfall": 0,
              "d_new_footfall": -4,
              "d_footfall_hours": 12,
              "d_avg_dwell_time": 0
          },
          "louis_philipe": {
              "brand_name_display": "LOUIS PHILIPPE",
              "floor_display": "First Floor",
              "footfall": "4.06K",
              "repeat_footfall": "3.38K",
              "new_footfall": 678,
              "footfall_hours": 227,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -6,
              "d_repeat_footfall": -4,
              "d_new_footfall": -15,
              "d_footfall_hours": -10,
              "d_avg_dwell_time": 0
          },
          "tbz": {
              "brand_name_display": "TBZ",
              "floor_display": "First Floor",
              "footfall": "4.1K",
              "repeat_footfall": "3.33K",
              "new_footfall": 762,
              "footfall_hours": 237,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -9,
              "d_repeat_footfall": -7,
              "d_new_footfall": -18,
              "d_footfall_hours": -19,
              "d_avg_dwell_time": 0
          },
          "esbeda": {
              "brand_name_display": "Esbeda",
              "floor_display": "First Floor",
              "footfall": "4.87K",
              "repeat_footfall": "3.71K",
              "new_footfall": "1.15K",
              "footfall_hours": 257,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": -12,
              "d_repeat_footfall": -10,
              "d_new_footfall": -20,
              "d_footfall_hours": -12,
              "d_avg_dwell_time": 0
          },
          "croma": {
              "brand_name_display": "Croma",
              "floor_display": "First Floor",
              "footfall": "6.47K",
              "repeat_footfall": "5.49K",
              "new_footfall": 979,
              "footfall_hours": 525,
              "avg_dwell_time": 5,
              "footfall_hex": "#000f84",
              "d_footfall": 8,
              "d_repeat_footfall": 9,
              "d_new_footfall": -1,
              "d_footfall_hours": 14,
              "d_avg_dwell_time": 0
          },
          "globus": {
              "brand_name_display": "Globus",
              "floor_display": "First Floor",
              "footfall": "6.24K",
              "repeat_footfall": "5.12K",
              "new_footfall": "1.12K",
              "footfall_hours": 328,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": -3,
              "d_repeat_footfall": -3,
              "d_new_footfall": -5,
              "d_footfall_hours": -9,
              "d_avg_dwell_time": 0
          },
          "urbana": {
              "brand_name_display": "Urbana",
              "floor_display": "First Floor",
              "footfall": "5.6K",
              "repeat_footfall": "4.57K",
              "new_footfall": "1.02K",
              "footfall_hours": 312,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": 6,
              "d_repeat_footfall": 6,
              "d_new_footfall": 7,
              "d_footfall_hours": 11,
              "d_avg_dwell_time": 0
          },
          "cadini": {
              "brand_name_display": "Cadini",
              "floor_display": "First Floor",
              "footfall": "5.94K",
              "repeat_footfall": "4.85K",
              "new_footfall": "1.09K",
              "footfall_hours": 366,
              "avg_dwell_time": 4,
              "footfall_hex": "#000f84",
              "d_footfall": 4,
              "d_repeat_footfall": 2,
              "d_new_footfall": 8,
              "d_footfall_hours": 14,
              "d_avg_dwell_time": 0
          },
          "adidas_ff": {
              "brand_name_display": "Adidas",
              "floor_display": "First Floor",
              "footfall": "6.84K",
              "repeat_footfall": "5.44K",
              "new_footfall": "1.4K",
              "footfall_hours": 361,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": 5,
              "d_repeat_footfall": 7,
              "d_new_footfall": 1,
              "d_footfall_hours": 19,
              "d_avg_dwell_time": 33
          },
          "sportszone": {
              "brand_name_display": "",
              "floor_display": "First Floor",
              "footfall": "6.98K",
              "repeat_footfall": "5.46K",
              "new_footfall": "1.52K",
              "footfall_hours": 337,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -24,
              "d_repeat_footfall": -24,
              "d_new_footfall": -22,
              "d_footfall_hours": -26,
              "d_avg_dwell_time": 0
          },
          "woodland": {
              "brand_name_display": "Woodland",
              "floor_display": "First Floor",
              "footfall": "7.88K",
              "repeat_footfall": "6.15K",
              "new_footfall": "1.73K",
              "footfall_hours": 411,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -26,
              "d_repeat_footfall": -24,
              "d_new_footfall": -34,
              "d_footfall_hours": -32,
              "d_avg_dwell_time": 0
          },
          "levis": {
              "brand_name_display": "Levi's",
              "floor_display": "First Floor",
              "footfall": "11.24K",
              "repeat_footfall": "9.12K",
              "new_footfall": "2.12K",
              "footfall_hours": 815,
              "avg_dwell_time": 4,
              "footfall_hex": "#001e87",
              "d_footfall": 12,
              "d_repeat_footfall": 12,
              "d_new_footfall": 13,
              "d_footfall_hours": 25,
              "d_avg_dwell_time": 25
          },
          "splash": {
              "brand_name_display": "Splash",
              "floor_display": "First Floor",
              "footfall": "10.61K",
              "repeat_footfall": "8.64K",
              "new_footfall": "1.97K",
              "footfall_hours": 600,
              "avg_dwell_time": 3,
              "footfall_hex": "#001e87",
              "d_footfall": -5,
              "d_repeat_footfall": -5,
              "d_new_footfall": -3,
              "d_footfall_hours": -4,
              "d_avg_dwell_time": 0
          },
          "pantaloons": {
              "brand_name_display": "Pantaloons",
              "floor_display": "First Floor",
              "footfall": "12.73K",
              "repeat_footfall": "9.94K",
              "new_footfall": "2.79K",
              "footfall_hours": 891,
              "avg_dwell_time": 4,
              "footfall_hex": "#002689",
              "d_footfall": -34,
              "d_repeat_footfall": -34,
              "d_new_footfall": -33,
              "d_footfall_hours": -42,
              "d_avg_dwell_time": 0
          },
          "puma": {
              "brand_name_display": "Puma",
              "floor_display": "First Floor",
              "footfall": "12.44K",
              "repeat_footfall": "9.8K",
              "new_footfall": "2.63K",
              "footfall_hours": 705,
              "avg_dwell_time": 3,
              "footfall_hex": "#002689",
              "d_footfall": 0,
              "d_repeat_footfall": 1,
              "d_new_footfall": -2,
              "d_footfall_hours": 10,
              "d_avg_dwell_time": 33
          },
          "ucb": {
              "brand_name_display": "United Colors of Benetton",
              "floor_display": "First Floor",
              "footfall": "14.21K",
              "repeat_footfall": "11.32K",
              "new_footfall": "2.89K",
              "footfall_hours": 957,
              "avg_dwell_time": 4,
              "footfall_hex": "#002a8a",
              "d_footfall": -32,
              "d_repeat_footfall": -31,
              "d_new_footfall": -36,
              "d_footfall_hours": -39,
              "d_avg_dwell_time": 0
          },
          "arrow": {
              "brand_name_display": "ARROW",
              "floor_display": "First Floor",
              "footfall": "14.36K",
              "repeat_footfall": "11.87K",
              "new_footfall": "2.49K",
              "footfall_hours": "1.3K",
              "avg_dwell_time": 5,
              "footfall_hex": "#002a8a",
              "d_footfall": -3,
              "d_repeat_footfall": -2,
              "d_new_footfall": -5,
              "d_footfall_hours": -5,
              "d_avg_dwell_time": 0
          },
          "nike": {
              "brand_name_display": "Nike",
              "floor_display": "First Floor",
              "footfall": "15.01K",
              "repeat_footfall": "12.29K",
              "new_footfall": "2.72K",
              "footfall_hours": "1.09K",
              "avg_dwell_time": 4,
              "footfall_hex": "#002a8a",
              "d_footfall": 1,
              "d_repeat_footfall": 3,
              "d_new_footfall": -7,
              "d_footfall_hours": 1,
              "d_avg_dwell_time": 0
          },
          "lavie": {
              "brand_name_display": "Lavie",
              "floor_display": "First Floor",
              "footfall": "17.23K",
              "repeat_footfall": "14.3K",
              "new_footfall": "2.93K",
              "footfall_hours": "1.54K",
              "avg_dwell_time": 5,
              "footfall_hex": "#002f8b",
              "d_footfall": -3,
              "d_repeat_footfall": -3,
              "d_new_footfall": -4,
              "d_footfall_hours": 4,
              "d_avg_dwell_time": 20
          },
          "bata": {
              "brand_name_display": "Bata",
              "floor_display": "First Floor",
              "footfall": "21.61K",
              "repeat_footfall": "17.07K",
              "new_footfall": "4.54K",
              "footfall_hours": "1.63K",
              "avg_dwell_time": 5,
              "footfall_hex": "#003b8d",
              "d_footfall": 18,
              "d_repeat_footfall": 20,
              "d_new_footfall": 12,
              "d_footfall_hours": 41,
              "d_avg_dwell_time": 0
          },
          "westside": {
              "brand_name_display": "Westside",
              "floor_display": "First Floor",
              "footfall": "23.04K",
              "repeat_footfall": "18.19K",
              "new_footfall": "4.84K",
              "footfall_hours": "1.43K",
              "avg_dwell_time": 4,
              "footfall_hex": "#00448f",
              "d_footfall": -22,
              "d_repeat_footfall": -21,
              "d_new_footfall": -25,
              "d_footfall_hours": -21,
              "d_avg_dwell_time": 0
          },
          "regal": {
              "brand_name_display": "Regal",
              "floor_display": "First Floor",
              "footfall": "23.8K",
              "repeat_footfall": "18.42K",
              "new_footfall": "5.39K",
              "footfall_hours": "2.09K",
              "avg_dwell_time": 5,
              "footfall_hex": "#004890",
              "d_footfall": -25,
              "d_repeat_footfall": -25,
              "d_new_footfall": -28,
              "d_footfall_hours": -31,
              "d_avg_dwell_time": 0
          },
          "skechers": {
              "brand_name_display": "Skechers",
              "floor_display": "First Floor",
              "footfall": "38.38K",
              "repeat_footfall": "30.14K",
              "new_footfall": "8.24K",
              "footfall_hours": "3.21K",
              "avg_dwell_time": 5,
              "footfall_hex": "#007899",
              "d_footfall": -11,
              "d_repeat_footfall": -11,
              "d_new_footfall": -10,
              "d_footfall_hours": -7,
              "d_avg_dwell_time": 0
          },
          "indian_terrain": {
              "brand_name_display": "Indian Terrain",
              "floor_display": "First Floor",
              "footfall": "42.5K",
              "repeat_footfall": "33.41K",
              "new_footfall": "9.09K",
              "footfall_hours": "3.84K",
              "avg_dwell_time": 5,
              "footfall_hex": "#008c9c",
              "d_footfall": 15,
              "d_repeat_footfall": 15,
              "d_new_footfall": 15,
              "d_footfall_hours": 39,
              "d_avg_dwell_time": 40
          }
      },
      "second_floor": {
          "valentine": {
              "brand_name_display": "",
              "floor_display": "Second Floor",
              "footfall": 599,
              "repeat_footfall": 498,
              "new_footfall": 101,
              "footfall_hours": 39,
              "avg_dwell_time": 4,
              "footfall_hex": "#000080",
              "d_footfall": -44,
              "d_repeat_footfall": -42,
              "d_new_footfall": -50,
              "d_footfall_hours": -54,
              "d_avg_dwell_time": -25
          },
          "w": {
              "brand_name_display": "W",
              "floor_display": "Second Floor",
              "footfall": 851,
              "repeat_footfall": 739,
              "new_footfall": 112,
              "footfall_hours": 76,
              "avg_dwell_time": 5,
              "footfall_hex": "#000080",
              "d_footfall": -78,
              "d_repeat_footfall": -76,
              "d_new_footfall": -87,
              "d_footfall_hours": -95,
              "d_avg_dwell_time": -80
          },
          "fusion_beat": {
              "brand_name_display": "Fusion Beats",
              "floor_display": "Second Floor",
              "footfall": 121,
              "repeat_footfall": 93,
              "new_footfall": 28,
              "footfall_hours": 0,
              "avg_dwell_time": 0,
              "footfall_hex": "#000080",
              "d_footfall": 26,
              "d_repeat_footfall": 25,
              "d_new_footfall": 29,
              "d_footfall_hours": "",
              "d_avg_dwell_time": ""
          },
          "wrangler": {
              "brand_name_display": "Wrangler",
              "floor_display": "Second Floor",
              "footfall": 201,
              "repeat_footfall": 182,
              "new_footfall": 19,
              "footfall_hours": 9,
              "avg_dwell_time": 3,
              "footfall_hex": "#000080",
              "d_footfall": -26,
              "d_repeat_footfall": -26,
              "d_new_footfall": -32,
              "d_footfall_hours": -100,
              "d_avg_dwell_time": -100
          },
          "bodhi_tree_spa": {
              "brand_name_display": "Bodhi Thai Spa",
              "floor_display": "Second Floor",
              "footfall": 318,
              "repeat_footfall": 288,
              "new_footfall": 30,
              "footfall_hours": 30,
              "avg_dwell_time": 6,
              "footfall_hex": "#000080",
              "d_footfall": 26,
              "d_repeat_footfall": 27,
              "d_new_footfall": 20,
              "d_footfall_hours": 27,
              "d_avg_dwell_time": 0
          },
          "unlimited": {
              "brand_name_display": "UNLIMITED",
              "floor_display": "Second Floor",
              "footfall": "2.42K",
              "repeat_footfall": "2.08K",
              "new_footfall": 336,
              "footfall_hours": 214,
              "avg_dwell_time": 5,
              "footfall_hex": "#000481",
              "d_footfall": -17,
              "d_repeat_footfall": -19,
              "d_new_footfall": -6,
              "d_footfall_hours": 38,
              "d_avg_dwell_time": 80
          },
          "envi_salon": {
              "brand_name_display": "Envi",
              "floor_display": "Second Floor",
              "footfall": "2.35K",
              "repeat_footfall": "2.03K",
              "new_footfall": 318,
              "footfall_hours": 243,
              "avg_dwell_time": 6,
              "footfall_hex": "#000481",
              "d_footfall": -19,
              "d_repeat_footfall": -17,
              "d_new_footfall": -32,
              "d_footfall_hours": -37,
              "d_avg_dwell_time": -17
          },
          "just_play": {
              "brand_name_display": "Justplay",
              "floor_display": "Second Floor",
              "footfall": "3.1K",
              "repeat_footfall": "2.5K",
              "new_footfall": 595,
              "footfall_hours": 164,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -11,
              "d_repeat_footfall": -11,
              "d_new_footfall": -9,
              "d_footfall_hours": -16,
              "d_avg_dwell_time": 0
          },
          "peter_england": {
              "brand_name_display": "Peter England",
              "floor_display": "Second Floor",
              "footfall": "4.02K",
              "repeat_footfall": "3.34K",
              "new_footfall": 683,
              "footfall_hours": 234,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -1,
              "d_repeat_footfall": 3,
              "d_new_footfall": -19,
              "d_footfall_hours": 7,
              "d_avg_dwell_time": 33
          },
          "octave": {
              "brand_name_display": "Octave",
              "floor_display": "Second Floor",
              "footfall": "2.88K",
              "repeat_footfall": "2.47K",
              "new_footfall": 412,
              "footfall_hours": 162,
              "avg_dwell_time": 3,
              "footfall_hex": "#000782",
              "d_footfall": -11,
              "d_repeat_footfall": -10,
              "d_new_footfall": -15,
              "d_footfall_hours": -19,
              "d_avg_dwell_time": 0
          },
          "soch": {
              "brand_name_display": "SOCH",
              "floor_display": "Second Floor",
              "footfall": "4.39K",
              "repeat_footfall": "3.62K",
              "new_footfall": 777,
              "footfall_hours": 837,
              "avg_dwell_time": 11,
              "footfall_hex": "#000782",
              "d_footfall": -32,
              "d_repeat_footfall": -31,
              "d_new_footfall": -39,
              "d_footfall_hours": -35,
              "d_avg_dwell_time": 0
          },
          "jugheads": {
              "brand_name_display": "Jug Heads & Citrus",
              "floor_display": "Second Floor",
              "footfall": "3.33K",
              "repeat_footfall": "2.75K",
              "new_footfall": 586,
              "footfall_hours": 548,
              "avg_dwell_time": 10,
              "footfall_hex": "#000782",
              "d_footfall": 37,
              "d_repeat_footfall": 36,
              "d_new_footfall": 40,
              "d_footfall_hours": 30,
              "d_avg_dwell_time": -10
          },
          "biba": {
              "brand_name_display": "Biba",
              "floor_display": "Second Floor",
              "footfall": "3.47K",
              "repeat_footfall": "2.9K",
              "new_footfall": 567,
              "footfall_hours": 208,
              "avg_dwell_time": 4,
              "footfall_hex": "#000782",
              "d_footfall": -19,
              "d_repeat_footfall": -17,
              "d_new_footfall": -33,
              "d_footfall_hours": -29,
              "d_avg_dwell_time": -25
          },
          "mustard": {
              "brand_name_display": "Mustard",
              "floor_display": "Second Floor",
              "footfall": "5.01K",
              "repeat_footfall": "4.07K",
              "new_footfall": 939,
              "footfall_hours": 235,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": -7,
              "d_repeat_footfall": -5,
              "d_new_footfall": -15,
              "d_footfall_hours": -3,
              "d_avg_dwell_time": 0
          },
          "mod": {
              "brand_name_display": "MAD OVER DONUTS",
              "floor_display": "Second Floor",
              "footfall": "6.18K",
              "repeat_footfall": "4.82K",
              "new_footfall": "1.36K",
              "footfall_hours": 331,
              "avg_dwell_time": 3,
              "footfall_hex": "#000f84",
              "d_footfall": 6,
              "d_repeat_footfall": 8,
              "d_new_footfall": -2,
              "d_footfall_hours": 19,
              "d_avg_dwell_time": 33
          },
          "manyawar": {
              "brand_name_display": "MANYAVAR",
              "floor_display": "Second Floor",
              "footfall": "5.25K",
              "repeat_footfall": "4.39K",
              "new_footfall": 855,
              "footfall_hours": 582,
              "avg_dwell_time": 7,
              "footfall_hex": "#000f84",
              "d_footfall": 10,
              "d_repeat_footfall": 13,
              "d_new_footfall": -9,
              "d_footfall_hours": 18,
              "d_avg_dwell_time": 0
          },
          "kaya": {
              "brand_name_display": "Kaya",
              "floor_display": "Second Floor",
              "footfall": "8.28K",
              "repeat_footfall": "6.91K",
              "new_footfall": "1.37K",
              "footfall_hours": "1.17K",
              "avg_dwell_time": 8,
              "footfall_hex": "#001384",
              "d_footfall": -17,
              "d_repeat_footfall": -16,
              "d_new_footfall": -20,
              "d_footfall_hours": -1,
              "d_avg_dwell_time": 25
          },
          "ritu_kumar": {
              "brand_name_display": "Ritu Kumar",
              "floor_display": "Second Floor",
              "footfall": "7.24K",
              "repeat_footfall": "5.93K",
              "new_footfall": "1.3K",
              "footfall_hours": 402,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -1,
              "d_repeat_footfall": 0,
              "d_new_footfall": -1,
              "d_footfall_hours": -10,
              "d_avg_dwell_time": 0
          },
          "ucb_kids": {
              "brand_name_display": "UNITED COLORS OF BENETTON KIDS",
              "floor_display": "Second Floor",
              "footfall": "8.39K",
              "repeat_footfall": "6.6K",
              "new_footfall": "1.78K",
              "footfall_hours": 411,
              "avg_dwell_time": 3,
              "footfall_hex": "#001384",
              "d_footfall": -6,
              "d_repeat_footfall": -4,
              "d_new_footfall": -13,
              "d_footfall_hours": -1,
              "d_avg_dwell_time": 0
          },
          "tommy_kids": {
              "brand_name_display": "TOMMY HILFIGER KIDS",
              "floor_display": "Second Floor",
              "footfall": "9.16K",
              "repeat_footfall": "7.42K",
              "new_footfall": "1.74K",
              "footfall_hours": 506,
              "avg_dwell_time": 3,
              "footfall_hex": "#001a86",
              "d_footfall": -21,
              "d_repeat_footfall": -21,
              "d_new_footfall": -21,
              "d_footfall_hours": -15,
              "d_avg_dwell_time": 33
          },
          "mothercare": {
              "brand_name_display": "Mother Care",
              "floor_display": "Second Floor",
              "footfall": "9.82K",
              "repeat_footfall": "7.45K",
              "new_footfall": "2.36K",
              "footfall_hours": 818,
              "avg_dwell_time": 5,
              "footfall_hex": "#001a86",
              "d_footfall": 1,
              "d_repeat_footfall": 0,
              "d_new_footfall": 2,
              "d_footfall_hours": -6,
              "d_avg_dwell_time": 0
          },
          "imara": {
              "brand_name_display": "IMARA",
              "floor_display": "Second Floor",
              "footfall": "9.44K",
              "repeat_footfall": "7.72K",
              "new_footfall": "1.71K",
              "footfall_hours": 585,
              "avg_dwell_time": 4,
              "footfall_hex": "#001a86",
              "d_footfall": -9,
              "d_repeat_footfall": -7,
              "d_new_footfall": -18,
              "d_footfall_hours": -18,
              "d_avg_dwell_time": -25
          },
          "wonderchef": {
              "brand_name_display": "Wonder Chef",
              "floor_display": "Second Floor",
              "footfall": "8.64K",
              "repeat_footfall": "6.88K",
              "new_footfall": "1.77K",
              "footfall_hours": 462,
              "avg_dwell_time": 3,
              "footfall_hex": "#001a86",
              "d_footfall": -7,
              "d_repeat_footfall": -6,
              "d_new_footfall": -10,
              "d_footfall_hours": -3,
              "d_avg_dwell_time": 0
          },
          "fabindia": {
              "brand_name_display": "Fabindia",
              "floor_display": "Second Floor",
              "footfall": "10.69K",
              "repeat_footfall": "8.68K",
              "new_footfall": "2.01K",
              "footfall_hours": "1.79K",
              "avg_dwell_time": 10,
              "footfall_hex": "#001e87",
              "d_footfall": 5,
              "d_repeat_footfall": 6,
              "d_new_footfall": -2,
              "d_footfall_hours": 9,
              "d_avg_dwell_time": 0
          },
          "hamleys": {
              "brand_name_display": "Hamleys",
              "floor_display": "Second Floor",
              "footfall": "10.77K",
              "repeat_footfall": "8.27K",
              "new_footfall": "2.5K",
              "footfall_hours": 870,
              "avg_dwell_time": 5,
              "footfall_hex": "#001e87",
              "d_footfall": 25,
              "d_repeat_footfall": 25,
              "d_new_footfall": 23,
              "d_footfall_hours": 35,
              "d_avg_dwell_time": 0
          },
          "myo_thai": {
              "brand_name_display": "Myo Thai Spa",
              "floor_display": "Second Floor",
              "footfall": "10.46K",
              "repeat_footfall": "8.45K",
              "new_footfall": "2.01K",
              "footfall_hours": 669,
              "avg_dwell_time": 4,
              "footfall_hex": "#001e87",
              "d_footfall": 10,
              "d_repeat_footfall": 9,
              "d_new_footfall": 14,
              "d_footfall_hours": 10,
              "d_avg_dwell_time": 0
          },
          "smash": {
              "brand_name_display": "Smaaash",
              "floor_display": "Second Floor",
              "footfall": "13.18K",
              "repeat_footfall": "10.61K",
              "new_footfall": "2.56K",
              "footfall_hours": "1.51K",
              "avg_dwell_time": 7,
              "footfall_hex": "#002689",
              "d_footfall": -9,
              "d_repeat_footfall": -9,
              "d_new_footfall": -9,
              "d_footfall_hours": -18,
              "d_avg_dwell_time": -14
          },
          "inch_of_gold": {
              "brand_name_display": "Inch Of Gold",
              "floor_display": "Second Floor",
              "footfall": "16.06K",
              "repeat_footfall": "12.66K",
              "new_footfall": "3.4K",
              "footfall_hours": "1.11K",
              "avg_dwell_time": 4,
              "footfall_hex": "#002f8b",
              "d_footfall": -33,
              "d_repeat_footfall": -32,
              "d_new_footfall": -35,
              "d_footfall_hours": -38,
              "d_avg_dwell_time": 0
          },
          "samsung": {
              "brand_name_display": "Samsung",
              "floor_display": "Second Floor",
              "footfall": "21.25K",
              "repeat_footfall": "16.51K",
              "new_footfall": "4.74K",
              "footfall_hours": "3.09K",
              "avg_dwell_time": 9,
              "footfall_hex": "#003b8d",
              "d_footfall": -2,
              "d_repeat_footfall": 0,
              "d_new_footfall": -8,
              "d_footfall_hours": -2,
              "d_avg_dwell_time": 0
          },
          "jnj": {
              "brand_name_display": "Gini & Jony",
              "floor_display": "Second Floor",
              "footfall": "22.56K",
              "repeat_footfall": "17.35K",
              "new_footfall": "5.22K",
              "footfall_hours": "1.73K",
              "avg_dwell_time": 5,
              "footfall_hex": "#00448f",
              "d_footfall": -8,
              "d_repeat_footfall": -6,
              "d_new_footfall": -15,
              "d_footfall_hours": -6,
              "d_avg_dwell_time": 0
          },
          "foodcourt": {
              "brand_name_display": "",
              "floor_display": "Second Floor",
              "footfall": "29.66K",
              "repeat_footfall": "23.29K",
              "new_footfall": "6.36K",
              "footfall_hours": "13.63K",
              "avg_dwell_time": 28,
              "footfall_hex": "#005b94",
              "d_footfall": 15,
              "d_repeat_footfall": 15,
              "d_new_footfall": 15,
              "d_footfall_hours": 37,
              "d_avg_dwell_time": 18
          },
          "meena_bazaar": {
              "brand_name_display": "Meena Bazaar",
              "floor_display": "Second Floor",
              "footfall": "36.88K",
              "repeat_footfall": "29.2K",
              "new_footfall": "7.68K",
              "footfall_hours": "4.45K",
              "avg_dwell_time": 7,
              "footfall_hex": "#007899",
              "d_footfall": -12,
              "d_repeat_footfall": -12,
              "d_new_footfall": -12,
              "d_footfall_hours": -28,
              "d_avg_dwell_time": -14
          },
          "max": {
              "brand_name_display": "Max",
              "floor_display": "Second Floor",
              "footfall": "40.26K",
              "repeat_footfall": "31.11K",
              "new_footfall": "9.15K",
              "footfall_hours": "5.09K",
              "avg_dwell_time": 8,
              "footfall_hex": "#00829b",
              "d_footfall": -11,
              "d_repeat_footfall": -11,
              "d_new_footfall": -11,
              "d_footfall_hours": -16,
              "d_avg_dwell_time": -12
          }
      }
  }
}

@Component({
  selector: 'app-heatmap-summary',
  templateUrl: './heatmap-summary.component.html',
  styleUrls: ['./heatmap-summary.component.scss']
})
export class HeatmapSummaryComponent implements OnInit {

  primaryMetrics = 'footfall';
  dateRange: any = 'range';
  selected = {startDate: moment, endDate: moment};
  floors = '';
  compareToSelect: any = 'range';
  compareToCustomDate = {startDate: moment, endDate: moment};
  isLoading: boolean;
  private alive = true;

  showHeatMap(response) {
    const svgNS = 'http://www.w3.org/2000/svg';
    const color_bar = response.legend['footfall_hex'];
    const color_bar_value = response.legend['Index']
    for (let i = 0; i < color_bar.length; i++) {
        const rect = document.createElementNS(svgNS, 'rect'); //to create a circle. for rectangle use 'rectangle'
        rect.setAttribute('id', `${i}`);
        rect.setAttribute('x', `${20+5 * i}`);
        rect.setAttribute('y', '5');
        rect.setAttribute('width', '5');
        rect.setAttribute('height', '20');
        rect.setAttribute('fill', color_bar[i]);
        rect.setAttribute('stroke', color_bar[i]);
        document.getElementById('mySVG').appendChild(rect);
    }


    const lg_data = response.data.lower_ground;
    const metric = response.metric;

    const id = [];
    for (const key in lg_data) { 
      id.push(key); 
    }

    id.map(_id => {
        $(`#${_id}`).css({ fill: lg_data[_id][metric + '_hex'], stroke: 'white' });

    });

    const lg = document.querySelectorAll('#LG');
    console.log(lg);
    for (let i = 0; i < lg.length; i++) {
      lg[i]['style']['fill'] = 'grey';
      lg[i]['style']['stroke'] = 'white';
    }


    $('rect').on('mouseover', function (evt) {
        const sid = this.id;



        $(this).css('cursor', 'pointer');




        if (sid !== 'LG') {

            const brand_name = lg_data[sid]['brand_name_display'];
            const color_index = lg_data[sid]['color_index'];
            const hex = lg_data[sid][metric + '_hex'];
            const json = {
                'footfall':
                {
                    'name': 'Footfall',
                    'value': lg_data[sid]['footfall'],
                    'change': lg_data[sid]['d_footfall']
                },
                'new_customer':
                {
                    'name': 'New Customers',
                    'value': lg_data[sid]['new_footfall'],
                    'change': lg_data[sid]['d_new_footfall']
                },
                'returning_customer':
                {
                    'name': 'Returning Customers',
                    'value': lg_data[sid]['repeat_footfall'],
                    'change': lg_data[sid]['d_repeat_footfall']
                },
                'footfall_hours':
                {
                    'name': 'Footfall hours',
                    'value': lg_data[sid]['footfall_hours'],
                    'change': lg_data[sid]['d_footfall_hours']
                },
                'avg_dwell_time':
                {
                    'name': 'Avg. Dwell Time (mins)',
                    'value': lg_data[sid]['avg_dwell_time'],
                    'change': lg_data[sid]['d_avg_dwell_time']
                },
                'sale':
                {
                    'name': 'Sales (INR)',
                    'value': '--',
                    'change': '--'
                }
            };
            const values = ['footfall', 'returning_customer', 'new_customer', 'footfall_hours', 'avg_dwell_time', 'sale'];
            document.getElementById(sid).style.stroke = 'white';
            document.getElementById(sid).style.strokeWidth = '3';
            const tooltip = document.getElementById('tooltip');
            const marker = document.getElementById('marker');
            const marker_range = document.getElementById('marker_range');
            marker_range.innerHTML = color_bar_value[color_index] + ' - '+ color_bar_value[color_index + 1];
            
            marker_range.setAttribute('x', String(20 + 5 * color_index))
            marker_range.setAttribute('y', '65');
            
            const marker_pos=20+5*color_index
            marker.setAttribute('transform', 'translate(' + marker_pos + ',25)');

            marker.style.fill = hex;
            tooltip.style.background = 'white';
            document.getElementById('tooltip').style.boxShadow = '0 4px 8px 0 ' + hex;
            document.getElementById('card-header').innerHTML = brand_name;
            document.getElementById('card-header').style.color = hex;
            values.forEach(value => {
                document.getElementById(`${value}-name`).innerHTML = json[value]['name'];
                document.getElementById(`${value}-value`).innerHTML = json[value].value;
                document.getElementById(`${value}-color`).innerHTML = (json[value].change > 0) ? `&#129033; ${json[value].change}%` : `&#129035; ${Math.abs(json[value].change)}%`;
                document.getElementById(`${value}-color`).style.color = (json[value].change > 0) ? 'green' : 'red';
            });


            tooltip.style.display = 'block';
            const x = parseInt($(this).attr('x'));
            const y = parseInt($(this).attr('y'));
            const H = parseInt($(this).attr('height')) * 0.5;
            const W = parseInt($(this).attr('width')) * 0.02;
            const width = $(this).width();
            const height = $(this).height();
            
            const parentOffset = $(this).parent().offset();
            const { top, left } = $(this).position();
            const relX = 1100 - (left - parentOffset.left) - (width * 0.35);
            const relY = 600 - (top - parentOffset.top) - (height * 0.35);
            if (relX > 800) {
              const leftX = left - parentOffset.left + (width * 0.35);
              tooltip.style.left = `${leftX}px`;
              tooltip.style.right = 'auto';
            } else {
              tooltip.style.left = 'auto';
              tooltip.style.right = `${relX}px`;
            }
            tooltip.style.bottom = `${relY}px`;
            console.log({ top, left }, 'position');
            console.log(parentOffset.top, parentOffset.left, 'parentOffset');
        }
    });
    // document.getElementById('tooltip').onmouseover((e : MouseEvent)=> {
    //   e.target.style.display = 'block';
    // });

    $('#tooltip').on('mousein', function () {
      $(this).css('display', 'block');
    });
  
    $('rect').on('mouseout', function () {
      const sid = this.id;
      if (sid !== 'LG' && isNaN(parseInt(sid, 10)) === true) {

          const marker = document.getElementById('marker');
          const marker_range = document.getElementById('marker_range');
          marker.style.fill = 'none';
          document.getElementById(sid).style.fill = lg_data[sid][metric + '_hex'];
          document.getElementById(sid).style.stroke = lg_data[sid][metric + '_hex'];
          const tooltip = document.getElementById('tooltip');
          tooltip.style.display = 'none';
          marker_range.innerHTML = '';
      }
    });
  }



  constructor(
    private auth: AuthService,
    private router: Router,

  ) { }

  changeMetrics(ev) {
  }
  selectFloors(ev) {
  }
  changeCompareTo(ev) {
  }
  compareToDateRange(ev) {
  }
  changeSelection(ev) {
  }

  ngOnInit() {
    this.isLoading = true;
   this.auth.getHeatMapData()
   .pipe(
    takeWhile(() => this.alive),
  )
   .subscribe(
      (results: any) => {
        this.isLoading = false;
        this.showHeatMap(results);
        console.log(results);
      },
      res => {
        console.log(res);
        this.router.navigate(['/']);
      }
   );
}
}
